export const GET_PLAYERS_START = 'players/getPlayersStart'
export const GET_PLAYERS_SUCCESS = 'players/getPlayersSuccess'
export const GET_PLAYERS_FAILURE = 'players/getPlayersFailure'
export const UPDATE_PLAYER_START = 'players/updatePlayerStart'
export const UPDATE_PLAYER_SUCCESS = 'players/updatePlayerSuccess'
export const UPDATE_PLAYER_FAILURE = 'players/updatePlayerFailure'